### ISSUE TITLE
Cloning lazy instantiated objects

### ISSUE THREAD

**Issue by theofidry** [Ocramius/ProxyManager#333]
If you have a proxy used to lazy instantiated object, cloning it will result in the instantiation of the said object. Is there any way to prevent that? Because this makes it impossible to use lazy instantiation in an immutable system.

To give a more real world use case, in the case of https://github.com/nelmio/alice, sometimes generating a fixture object may result in resolving other objects. For example if you have:

```yaml
Dummy:
  dummy1:
    relatedDummy: '@dummy*'
  dummy0: {}
```

When generating `dummy1`, `@dummy*` will match `dummy0` and so `dummy0` will be generated before `dummy1`. In certain cases however, for example:

```yaml
Dummy:
  dummy{1..10}:
    relatedDummies: '3x @dummy*' # means will construct and array where each element will be @dummy*
```

This strategy fails because you may have cyclic dependencies. Those cyclic dependences are actually perfectly valid and is not something that should be avoided, but it will fail is because for example `dummy1` needs `dummy2` to be generated first, and `dummy2` needs `dummy3`, but `dummy3` needs `dummy1`, which cannot be generated yet...

There is two ways to fix that:

1. Instantiate all objects first, but this problem persist if you have those dependencies at the instantiation level, i.e. for example:

```yaml
Dummy:
  dummy{1..10}:
    __construct: ['3x @dummy*']
```

2. lazy instantiate the objects. So when `dummy1` needs `dummy2`, you stop at that and you don't care yet how `dummy2` is generated.

The issue is that the library enforces immutability almost everywhere, for example 
[here](https://github.com/nelmio/alice/blob/master/src/Definition/Property.php#L36), making use of https://github.com/myclabs/DeepCopy. The resulting issue is that some cloning are done too early for the usage of a proxy to be of any use.
